/* eslint-disable @next/next/no-img-element */
import Head from "next/head"
import { useState, useEffect } from "react"

export default function Home() {
  const [advice, setAdvice] = useState({
    id: "117",
    text: "The higher up you are in a company, the more likely it is that your boss is a psychopath.",
  })

  const [nextAdvice, setNextAdvice] = useState(false)

  useEffect(() => {
    if (nextAdvice) {
      fetch("https://api.adviceslip.com/advice")
        .then(res => res.json())
        .then(data => {
          setAdvice({ id: data.slip.id, text: data.slip.advice })
          setNextAdvice(false)
        })
    }
  }, [nextAdvice])

  return (
    <>
      <Head>
        <title>Advice generator app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.png" />
      </Head>
      <main className="flex h-screen w-screen items-center justify-center bg-[hsl(218,_23%,_16%)]">
        <section className="relative flex  w-2/5 min-w-[22rem] flex-col items-center rounded-lg bg-[hsl(217,_19%,_24%)] px-8 pt-12 pb-20">
          <h6 className="font-manrope text-xs font-semibold tracking-[0.3rem] text-[hsl(150,_100%,_66%)]">
            ADVICE #{advice.id}
          </h6>
          <h1 className="mt-8 text-center text-[1.75rem] font-semibold text-[hsl(193,_38%,_86%)] before:content-['“_'] after:content-['_”']">
            {advice.text}
          </h1>
          <img
            className="mt-8 hidden lg:block "
            src="pattern-divider-desktop.svg"
            alt=""
          />
          <img
            className="mt-8 lg:hidden "
            src="pattern-divider-mobile.svg"
            alt=""
          />
          <div
            onClick={() => {
              setNextAdvice(true)
            }}
            className="absolute bottom-[-1rem] flex h-14 w-14 cursor-pointer items-center justify-center rounded-full bg-[hsl(150,_100%,_66%)] hover:shadow-[0px_0px_20px_2px_hsl(150deg_100%_66%)]"
          >
            <img src="icon-dice.svg" alt="" />
          </div>
        </section>
      </main>
    </>
  )
}
